---
name: CI
on: [push, workflow_dispatch]

jobs:
  go-build:
    name: Build go${{ matrix.go }}-${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.16', '1.17']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Install go dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./...
      - name: Generate code coverage
        if: matrix.os == 'ubuntu-latest' && matrix.go == '1.17'
        run: |
          go test ./... -coverprofile cover.out
          go tool cover -func cover.out | grep total | awk '{print $3}' | xargs -I {} curl \
          --header "Authorization: Token ${{ secrets.SERIESCI_TOKEN }}" \
          --data "{ \"value\":\"{}\", \"sha\":\"${GITHUB_SHA}\"}" \
          https://seriesci.com/api/deversmann/gotemp/coverage/one
      - name: Build the project
        run: go build ./...

...